# Generated by Django 3.2 on 2021-05-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210501_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='summary',
        ),
    ]
