# Generated by Django 3.2 on 2021-05-01 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='webapp.category', verbose_name='Product Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product_pics', verbose_name='Product Image'),
        ),
    ]
