# Generated by Django 3.2 on 2021-05-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210501_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='product_pics/default.jpg', null=True, upload_to='product_pics', verbose_name='Product Image'),
        ),
    ]
