# Generated by Django 3.2 on 2021-05-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_review_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('moderate', 'Can moderate the review')], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
